# Generated by Django 5.2 on 2025-04-18 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0003_rename_nombreproducto_producto_nombre_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
