# Generated by Django 5.2 on 2025-04-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0006_juegos_categoria_juegos_producto_categoria_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='categoria_juegos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablas.categoriajuego'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria_productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablas.categoriaproducto'),
        ),
    ]
