# Generated by Django 5.2 on 2025-04-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0007_alter_juegos_categoria_juegos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigopostal',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(default=123, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(default='josue21', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_juegos/'),
        ),
        migrations.AddField(
            model_name='juegos',
            name='ventas',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licencias',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_licencias/'),
        ),
        migrations.AddField(
            model_name='licencias',
            name='ventas',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_productos/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.PositiveBigIntegerField(),
        ),
    ]
