# Generated by Django 5.2 on 2025-04-27 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0008_rol_cliente_codigopostal_cliente_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tablas.rol'),
        ),
    ]
