# Generated by Django 5.2 on 2025-05-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0012_carrito_detalleventa_rename_categoriajuego_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
