# Generated by Django 5.2 on 2025-05-04 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0015_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tablas.usuario'),
        ),
    ]
