# Generated by Django 5.2 on 2025-04-17 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=150)),
                ('precio', models.PositiveIntegerField()),
                ('categoria', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='lastname',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='firstname',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
