# Generated by Django 5.2 on 2025-04-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_producto_rename_lastname_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombreproducto',
            new_name='nombre_producto',
        ),
    ]
